#!/bin/bash

# Edit these lines to reflect your local environment
BOIDS_HOME=~/Documents/Development/Clojure/Boids
JLINE_JAR=~/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar

# The rest should be OK
CLOJURE_JAR=$BOIDS_HOME/lib/clojure-1.1.0.jar
CLOJURE_CONTRIB_JAR=$BOIDS_HOME/clojure-contrib-1.1.0.jar
BOIDS_SRC_PATH=$BOIDS_HOME/src
CLASSPATH=$JLINE_JAR:$CLOJURE_JAR:$CLOJURE_CONTRIB_JAR:$BOIDS_SRC_PATH:$CLASSPATH
# Run with YourKit profiler
JVM_ARGS="-server -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8888 -Xincgc -Xms384m -Xmx384m -XX:NewSize=128m -XX:MaxNewSize=128m"

java $JVM_ARGS -cp $CLASSPATH jline.ConsoleRunner clojure.main